---
development:
  secret_key_base: a6082cbd03854d0be914910d1ba97fde4ac72d3516a17b644cf67652b2bed76fee3748ddf0a826520ee87a05ff151466d0c88b7bf938e68e55b74a7779e771b7
  otp_key_base: 886f4021260f9932ebb3c5531d6b2a70bac43078c441e6fa343a22ac4d16d3725484b1c2399fb7678c7b27f92297e1bed353818f6606e6094a3b7f5ca90f3006
  db_key_base: 96087d3ffdc3238233eb162b00d602b1e0e4717533d62cc176720fa3f4074c94ea408ab4664e855934acab3431fa5a571c85872c6e16fc60d96e9b0c42034784
  jws_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAwh8T0XcU3G9QZ+Mglxtpd+nWltA+dUjEOzw/Hjjz5P9Hmtpd
    nLbg0qjnQqNCYhcA2a5txvGxpq3IaOLM4glqxbnZTtNiR0+DkzNxsoW5G8b/EG3V
    S54WpZdUIbGTy0zVg6PIyQ6l3GClC0t+xEL048mO0lCELNBKsIfpcfcPDZ7lDOEc
    qos0iB6ATDqvZzIOZyO70MXBHnvtKHWx74FflaKAUq7rwiQTJT1j+i8tBk4pVKeq
    Fgv69lnbe72BySfDM8TpqyTx7mD2Wr1GJ/f62sDExeli+R5Henubyp807sY3c2L+
    CcUWNqXprDkRMMmC/pTYokTUHl1+TmvAubr4bwIDAQABAoIBAEiNMO0CoqtYdya8
    vrt7JUoJ/YfUQOO41I6HD9gN1SnrNynrHz2pJBHXyscfGXpruoehJ6pJPupa3SJG
    UejRODS6JzvMyVh5oWVsvrvIOszk7QOI6UUfyrsM+ga1xdUf3FUc67gpX1gkTssP
    5ksX80sHU/fK2/ubxa6AvYE4o0mlSKjPsQTz6kKnoBkmeQTOfrpE+r2uUw4m4yqi
    Q5febNTaBhTYRZwFs63/YCRWADl+6t7c+4NCFFB6VS+BlsN2IJdyx6AJdn/xYXoB
    qL11yULODbcmbvxIst18TMJCeIOUIIrZkH4wxX1ppUlnRB269WGsZzYoTxCdyWtZ
    jliuD4ECgYEA5N7f1pXaO8nvx+gN4TxwJzgOG4EtB3K+CQB/fOEEzDqz36h6g7jN
    Bdi7SjyslhqIeOHXQFPcAWAqkT/miBNY7Nq6Ppq+k/MlY0CO5ThMWW+LPHX7OVD3
    9PTHL4x/Y4Ac7A81dwOhVwixxxPqSviVGV9BUYq4pAc4c4OcjUSpHk8CgYEA2SG7
    MAAc5wgzlTQM17+Hm/d25glkldaH7TZOpVNcsOtydBx/wdqbo1gj45AAq8maytSZ
    qf2+meL0eOQfUXNI+TKbg+zKYfrmRnUDmmhxYxRiiAck7WgbII/fVZPwgZ+xd2HQ
    jrKua9DsT2EYzrzS0009/QAZcCYPgvkZeQqLG+ECgYEA3JyJHwsrZV5tp0BjwKzF
    XsiFsLV/diKAU6ULPpCYU1RydjCsh7PmzK/xOMnrgnTo/7ySBAvRkfHklkYGLTyZ
    BxZ/WEFJWsuRSm68Tu9JiRwgFpOTKdiGarRYG9lOIdcoCdNPMf1p078pvj/QI5wh
    /Gb5S2RwPoxHOfGvQezhJ7kCgYEArHRSDCnKyuSEs7iHisQgnQvLb6F+NlQR2aIM
    jNrM/+fBG9+WyQ0sGGxk9NTm84pIW1jIQ2+59td/fJUTGsoJ54L+aaWkiHWSd9tw
    ZS8W/66tI4UpGzZYdWBP7dR2bT284ijaULwyNIfXaKSh43GtsQ3kchGmIqDYKRpX
    1P8+xYECgYAL/yPsx0x4NT9Zg3rrOzVJ2ISZH7U5wBqxi7cyF83n6eCKTs4EvAtA
    5ncYipPZ7/TrZl9SSTrCwojLz5F0AbLerG1juBRK/YOPQY1L4qhOKaKKCl6u6OPU
    cbzG0qtYWZQ8SStixgmhllLHeN45tC0Csh/T5GwB7ZBS1ffLym4ZhQ==
    -----END RSA PRIVATE KEY-----
test:
  secret_key_base: 224cad7caca2b23cef9c1b16c7a2804138ddf5046dee87c7595c86f3c1443e3c1d1670af18f92f2b691b42a51beb5273a2503e558d7f4e609fdcfdfd983bc2bd
production:
  secret_key_base: 969e45fdc9df0572525fc3ea1d4d5447c2403c82d3b55e67fc38a145c012b32535c42bee18591dbebaf5dc4f497205e8da69afdeae747531aa51bcfefab16650
  otp_key_base: 2301eb99573f2109b976a5c4dddc2fc4f9cee54e5ab4948089d2de90b18c6e54152a6d54562d7f2905aa970b484a4da0c6232d166d309975538138c437c1927f
  db_key_base: 6c6926c7108c6b1b8d6444dc1af5ed81b6dacdb2545f209f2d21297f300fa2249b04dc138e756bc68163a7826dd01c0bd6677c34f876dc3c9d5db123cbcd17f7
  jws_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEArg+gJA+AaghpMEP7L1QHxuXTLyHGhCiors5kwC3JI2nkgtsP
    ruLzjEWlZ+F+gVPpUZJ4ygRBxaC3uHrt72AyWVCMhzrTyuwk1uCvCmt3ykbxP9aB
    aTbT421MjIrFVRxa+XkqCFOkQLjQfy2ONTeCTK2NtYiC/rxbf0p1zaBKDNiHzmIT
    f91dgJWq9PAYUO4/2UDPsJmCzCbQNDPwO5ESEORwsfFRBgU1a6Z/gjqb7Dto5FYp
    faNQ2FgGO6tVIJZH4EQexRZ6msjOi+GDDQ542/HOarToI6wfozAAcdZUk7SR49gU
    AHO+Gutuu3FAKYYIXnNDs/qTnro7JoQl/5LgMwIDAQABAoIBAQCZITYJg3m9zth7
    ldMNuCd/XAGGnXhAHGUKJJmOWLlzZl2aoY4Slacd6MeztDXPITtKgEmzsDsM2m/G
    5J8e0Mp6uNpoveBFzao7QD++Mv2X/wGO3+/J2Gpg0m9d1Vf1oJSIlYfc+3itV+pV
    eIZ7WvJO8wCQjCByatM0ERXCaRm8Ye4Umafp7IY6QGLfLzcRK9IZ6ChDZ7J2tZjD
    WWDBGEYMqG8UuldJtD4Rizn0TZVB0TfpzqIdz8lauurHFWJwaflJ5AS+BJYmCPWQ
    7cIyHaCOr5W4YggPhe7YDpl5SyhsKaeYn0IsDt5XDnU+EQ0PEfsKodHNOZH0xUOA
    0kLv8XaBAoGBAOHPFxpayAyXeEnlN3X2MrFhiBlKhO3QR3OUe4O4BGbo7s3ibBsc
    pVEPVNZveu40m75qu+FNXUOl0pwwj27bbgOBNeyn7kZ+dFD9eJSqnI/6FWRmyR0p
    DyUPD/XjB42PaxWY/dGUHscBSGSieRzNuJsSrucqkwYIYsBfa43e+AB5AoGBAMVV
    U3FVBFYaI9I7uPYurHsngUpBxzDtoNjfSySbvBfLAfsOtLhKlHbS2M1p0BUWC5tL
    SionUFs50culcnUcJX0m+s6ud7d0rL6EDvpkJpfgDH1yCY66eJzP4gPGF+hWpq0N
    ejK+YX5Wf6Q0AiQjuBHF+Sla7ZPYqbWlAX0oOPMLAoGAeLQSTWwpc1GkYxu7wbqQ
    7nCMJ7jFxbmH+ChuvcIn2Dq7LCLUVsnBNMtVNirxM1O7zNWRCKYqLHb/Va4/faqd
    7BGtmYtKuzPtST20rwNkHTI5LSokZwoDpnOevHlXGDyJqUnWo6jhqs7su559zv/I
    plweUkNXw+nHn71h6Lw/JUECgYAfIks8AlHg09b7AHk6PjrwY1c+xAoNajCKhxBw
    AjI2/sydM8DHotyxsqqKHju6V/QU2FgnNnSzL/gtzTi1yW8Qw+mmWliBFWN725IR
    Z2O/apYN5MQlRL5q31GljseO3L0HaKzy/J6dNECHQ71ivk/4Xefl4nbBcNm10wbd
    HE9/6QKBgQCKjyKUNBaIMq2vV1LHDZe/pyzedjGIbuUR+/kTwxe89wfqaDHfCvTe
    nwDSJPvNpiQ6TMxzsMWWc1z2iNlUI6OUxIXnAZ5s3fIm2StUNe2QvIc0fgfLdJLc
    lfWScJxcf+ESy6DrWQ6GUgKS/GfZVi2+DGVEx94pZwCjaWj5z2Y9Zg==
    -----END RSA PRIVATE KEY-----
