development:
  weixin:
    openid: gh_7eca389a5ba0
    #gh_7eca389a5ba0
    appid: wx1bd01df52c6ba150
    appsecret: "3c572f5c20707445a90fa97d2da7749f"
    aeskey: KS7nrcr7KV4tUco5Tvj6k6TzOT7VvSgj8O2xZv6wImr
    token: catchzino33333

production:
  weixin:
    openid: gh_7eca389a5ba0
    #gh_7eca389a5ba0
    appid: wx1bd01df52c6ba150
    appsecret: "3c572f5c20707445a90fa97d2da7749f"
    aeskey: KS7nrcr7KV4tUco5Tvj6k6TzOT7VvSgj8O2xZv6wImr
    token: catchzino33333